# Generated by Django 5.1 on 2024-08-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(decimal_places=20, max_digits=100),
        ),
    ]
