# Generated by Django 5.1 on 2024-08-11 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_price_alter_payment_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Edición'), (2, 'Cancelado'), (3, 'Pagado')], default=1),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product'),
        ),
    ]
