version: '3.9'

services:
  django-app:
    restart: always
    container_name: django-app
    image: my-django-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # env_file: ./backend/.env
    environment:
      DEBUG: True
      SECRET_KEY: "django-insecure-jizyjlj_lvn@%m+g43c(s2$7*%4h0kqslhw85zcs#^jgsqjp36"
      DATABASE_URL: "postgres://admin:admin123@django-db:5432/inventory_management"
      ALLOWED_HOSTS: ""
      DJANGO_SUPERUSER_USERNAME: "admin"
      DJANGO_SUPERUSER_EMAIL: "admin@example.com"
      DJANGO_SUPERUSER_PASSWORD: "adminpassword"
    depends_on:
      - django-db

  web-app:
    restart: always
    container_name: web-app
    image: my-web-app-react
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - 8282:8282
    environment:
      VITE_API_URL: http://localhost:8000
    
  django-db:
    container_name: django-db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: inventory_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
